version: "3.8"

networks:
  deliveroo: null

volumes:
  postgress: null

services:
  api:
    build:
      context: api
    container_name: deliveroo-api
    volumes: ["./api/src:/src/src"]
    networks: ["deliveroo"]
  
  app:
    build:
      context: app
    container_name: deliveroo-app
    networks: ["deliveroo"]

  www:
    build:
      context: www
    container_name: deliveroo-www
    networks: ["deliveroo"]
    ports: ["443:443"]